project:
  type: book

book:
  title: "Fynnli's Space Adventure"
  author: "Randi Bolt, ChatGPT, and starryai"
  date: "4/20/2023"
  chapters:
    - index.qmd
    - part: quarto/cc.qmd
      chapters:
        - quarto/cc_ch1.qmd
        - quarto/cc_ch2.qmd
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: sketchy
  pdf:
    documentclass: scrreprt



